computerScience:
  - https://us02web.zoom.us/j/83675875353?pwd=SjZtVmVnWGJPVTZJTmtQVzFmUlBjZz09
  - https://us02web.zoom.us/j/81334963275?pwd=enZ6WVlhcUtsK0oxL0xQeHJlWTJiZz09
  - https://us02web.zoom.us/j/86775401910?pwd=V0hTbC9MMm9XcmNCVTJjYUdkNE1BUT09

frontend:
  - https://meet.google.com/qyd-cqet-quc

english:
  - https://zoom.us/j/94501547418?pwd=aWk0eHBEZHpSR2dyVmNuamRiWC9QQT09
  - https://zoom.us/j/96466373299?pwd=Z3Z6TmVnTUNFQTRQRWZNbkgyMGNGdz09
  - https://zoom.us/j/92859666868?pwd=ZExmYTd2OUdZMVJpSFRPdE1jZmptQT09

physics:
  - https://us02web.zoom.us/j/83120913611?pwd=QndJMHZwanVreHRDcVdNL2RXM1B2dz09
  - https://us02web.zoom.us/j/81419545777?pwd=eENnOXZaT0x4S1pBNDE4bHVacGUxdz09
  - https://us02web.zoom.us/j/83537720276?pwd=OHhaT0Q3N3ZPQUJZRzQxOVFRWmgzQT09
